# -*- coding: utf-8 -*-
"""matrizEscalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9_9pCzmt9rvQRihDzh74752c0iWLOil
"""

import numpy as np

A = np.array([
    [2, 3, 8],
    [6, 0, 4],
    [1, 5, 7]
])

x = 3

print("Matriz Original A:")
print(A)
print(f"\nEscalar α = {x}")

linhas, colunas = A.shape

resultado = np.zeros((linhas, colunas), dtype=int)

for i in range(linhas):
    for j in range(colunas):
        resultado[i][j] = A[i][j] * x

print("\nResultado da multiplicação αA:")
print(resultado)

print("\nVerificação usando a função do NumPy:")
print(x * A)

print("\nNossa implementação corresponde à multiplicação do NumPy:", np.array_equal(resultado, x * A))