# -*- coding: utf-8 -*-
"""matrizDiagonal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WfKonxZnVOyUwnP_M3ffHkqZTcW1pjP4
"""

matriz_a = [
    [2, 0, 0],
    [0, 1, 0],
    [0, 0, 7]
]

def imprimir_matriz(matriz, nome):
    print(f"Matriz {nome}:")
    for linha in matriz:
        print(linha)
    print()

def verificar_diagonal(matriz):
    linhas = len(matriz)

    if linhas == 0:
        return False

    colunas = len(matriz[0])
    for linha in matriz:
        if len(linha) != colunas:
            return False

    if linhas != colunas:
        return False

    eh_diagonal = True
    for i in range(linhas):
        for j in range(colunas):
            if i != j and matriz[i][j] != 0:
                eh_diagonal = False
                return eh_diagonal

    return eh_diagonal

imprimir_matriz(matriz_a, "A")

if verificar_diagonal(matriz_a):
    print("A matriz A é diagonal.")
else:
    print("A matriz A não é diagonal.")