# -*- coding: utf-8 -*-
"""matrizTransposta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ah8yUvJEhUgcigonsWZLDeOMHtfIcNv
"""

import numpy as np

A = np.array([
    [2, 3, 8],
    [6, 0, 4],
    [1, 5, 7]
])

print("Matriz Original A:")
print(A)

linhas, colunas = A.shape

transposta = np.zeros((colunas, linhas), dtype=int)

for i in range(linhas):
    for j in range(colunas):
        transposta[j][i] = A[i][j]

print("\nMatriz A Transposta:")
print(transposta)

print("\nVerificação usando a função transposta do NumPy:")
print(A.T)

print("\nNossa implementação corresponde à transposta do NumPy:", np.array_equal(transposta, A.T))