# -*- coding: utf-8 -*-
"""matrizIdentidade.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6uuz-FrTiXEu3cgc0GkcRanee2a6Mg3
"""

matriz_a = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

def imprimir_matriz(matriz, nome):
    print(f"Matriz {nome}:")
    for linha in matriz:
        print(linha)
    print()

def verificar_identidade(matriz):
    linhas = len(matriz)

    if linhas == 0:
        return False

    colunas = len(matriz[0])
    for linha in matriz:
        if len(linha) != colunas:
            return False

    if linhas != colunas:
        return False

    eh_identidade = True
    for i in range(linhas):
        for j in range(colunas):
            if (i == j and matriz[i][j] != 1) or (i != j and matriz[i][j] != 0):
                eh_identidade = False
                return eh_identidade

    return eh_identidade

imprimir_matriz(matriz_a, "A")

if verificar_identidade(matriz_a):
    print("A matriz A é uma matriz identidade.")
else:
    print("A matriz A não é uma matriz identidade.")