# -*- coding: utf-8 -*-
"""multiplicacaoMatrizes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1tm9nhrxRnD2I8IYc36Rk5LLZ0cNQDE
"""

matriz_a = [
    [1, 2, 3],
    [4, 5, 6]
]

matriz_b = [
    [7, 8],
    [9, 10],
    [11, 12]
]

def imprimir_matriz(matriz, nome):
    print(f"Matriz {nome}:")
    for linha in matriz:
        print(linha)
    print()

def verificar_multiplicacao(matriz_a, matriz_b):
    colunas_a = len(matriz_a[0])
    linhas_b = len(matriz_b)

    if colunas_a == linhas_b:
        return True
    else:
        return False

def multiplicar_matrizes(matriz_a, matriz_b):
    linhas_a = len(matriz_a)
    colunas_a = len(matriz_a[0])
    colunas_b = len(matriz_b[0])

    matriz_resultado = []
    for i in range(linhas_a):
        matriz_resultado.append([0] * colunas_b)

    for i in range(linhas_a):
        for j in range(colunas_b):
            for k in range(colunas_a):
                matriz_resultado[i][j] += matriz_a[i][k] * matriz_b[k][j]

    return matriz_resultado

imprimir_matriz(matriz_a, "A")
imprimir_matriz(matriz_b, "B")

if verificar_multiplicacao(matriz_a, matriz_b):
    print("É possível multiplicar as matrizes A e B, pois o número de colunas de A é igual ao número de linhas de B.")

    resultado = multiplicar_matrizes(matriz_a, matriz_b)

    imprimir_matriz(resultado, "Resultado (A x B)")
else:
    print("Não é possível multiplicar as matrizes A e B, pois o número de colunas de A é diferente do número de linhas de B.")